# Generated by Django 5.0.7 on 2024-07-15 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPOUpcoming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icons', models.FileField(upload_to='home/')),
                ('company_name', models.CharField(max_length=100)),
                ('company_link', models.URLField()),
                ('price_band', models.CharField(max_length=50)),
                ('open_date', models.DateField(auto_now_add=True)),
                ('close_date', models.DateField(auto_now_add=True)),
                ('issue_size', models.CharField(max_length=50)),
                ('issue_type', models.CharField(max_length=50)),
                ('listing_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
