# Generated by Django 5.0.7 on 2024-07-16 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_ipoupcoming_delete_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaqModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('ans1', models.CharField(max_length=300)),
                ('ans2', models.CharField(max_length=300)),
                ('ans3', models.CharField(max_length=300)),
                ('ans4', models.CharField(max_length=300)),
                ('ans5', models.CharField(max_length=300)),
            ],
        ),
    ]
